### ISSUE TITLE
Fix linking error on MinGW

### ISSUE THREAD

**Issue by loreglean** [loreglean/lantern#11]
``[ 95%] Linking CXX executable examples\empty_app\empty_app.exe \cmake-3.3.0-win32-x86\bin\cmake.exe -E cmake_link_script CMakeFiles\empty_app.dir\link.txt --verbose=1 \cmake-3.3.0-win32-x86\bin\cmake.exe -E remove -f CMakeFiles\empty_app.dir/objects.a \mingw32-i686-5.1.0-release-posix-sjlj-rt_v4-rev0\bin\ar.exe cr CMakeFiles\empty_app.dir/objects.a @CMakeFiles\empty_app.dir\objects1.rsp \mingw32-i686-5.1.0-release-posix-sjlj-rt_v4-rev0\bin\g++.exe -std=gnu++0x -Wall -Wno-comment -mwindows -Wl,--whole-archive CMakeFiles\empty_app.dir/objects.a -Wl,--no-whole-archive -o examples\empty_app\empty_app.exe -Wl,--out-implib,libempty_app.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\empty_app.dir\linklibs.rsp /SDL2-devel-2.0.3-mingw/lib/x86/SDL2main.lib(./Release/SDL_windows_main.obj):(.text[_main]+0x0): multiple definition of `main' /mingw32-i686-5.1.0-release-posix-sjlj-rt_v4-rev0/bin/../lib/gcc/i686-w64-mingw32/5.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x0): first defined here Warning: corrupt .drectve at end of def file collect2.exe: error: ld returned 1 exit status``

**Comment by TheVice** [comment]
It may funny, but today when I merge [MinGW into vicemaster](https://github.com/TheVice/lantern/commit/a33eea540ddc13e7caa37de86f9674531bffdf41) I found that linking is OK. So I start investigate, and first of all reverting to MinGW ... but it also too OK to linking.
So I apologize for false alarm. But it better to check on own environment.

How that happen, actually used temporarily CMakeLists.txt, that do not saved, to deal with founding or not FreeType, so I suppose reason may be in that file.

P.S.
I steal, on own environment, do not deal with found or not FreeType (used [freetype-2.3.5-1-bin.zip](http://sourceforge.net/projects/gnuwin32/files/freetype/2.3.5-1/)) with original CMakeLists.txt, so now used next modification:
```find_package(SDL2IMAGE REQUIRED)
if(NOT MSVC AND NOT UNIX)
    string(REPLACE "\\" "/" FREETYPEDIR $ENV{FREETYPEDIR})
    set(FREETYPE_INCLUDE_DIRS ${FREETYPEDIR}/include ${FREETYPEDIR}/include/freetype2)
    set(FREETYPE_LIBRARY ${FREETYPEDIR}/lib/libfreetype.dll.a)
endif()
find_package(Freetype REQUIRED)```

**Comment by loreglean** [comment]
I'll first check it on my own pc and then will close this one if everything's fine

**Comment by loreglean** [comment]
I've checked it and linking is fine on mingw-32 (didn't check 64)
Just make sure you're using right libraries (all of them should be compiled for mingw-32)

Found some specific issues with ui_label implementation, will fix them later
